/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Donorform.java
 *
 * Created on Jan 3, 2014, 11:56:43 PM
 */
package forms;

/**
 *
 * @author Administrator
 */
public class Donorform extends javax.swing.JFrame {

    private String submittedUsername;

    public String getSubmittedConfirmpassword() {
        return submittedConfirmpassword;
    }

    public void setSubmittedConfirmpassword(String submittedConfirmpassword) {
        this.submittedConfirmpassword = submittedConfirmpassword;
    }

    public String getSubmittedPassword() {
        return submittedPassword;
    }

    public void setSubmittedPassword(String submittedPassword) {
        this.submittedPassword = submittedPassword;
    }

    public String getSubmittedUsername() {
        return submittedUsername;
    }

    public void setSubmittedUsername(String submittedUsername) {
        this.submittedUsername = submittedUsername;
    }
    private String submittedPassword;
    private String submittedConfirmpassword;
    private String submittedFullName;
    private int submittedAge;
    private String submittedGender;
    private String submittedPhone;
    private String submittedCity;
    private String submittedState;
    boolean returnFromDonorBL;
    boolean returnFromDonorRegistrationBL;

    /**
     * Creates new form Donor form
     */
    public Donorform() {
        initComponents();
        lWarning.setText(null);
        sAge.setValue(20);
        rMale.setSelected(true);
        rMale.setActionCommand("Male");
        rFemale.setActionCommand("Female");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButtonGroup = new javax.swing.ButtonGroup();
        pFieldPanel = new javax.swing.JPanel();
        lState = new javax.swing.JLabel();
        rFemale = new javax.swing.JRadioButton();
        sAge = new javax.swing.JSpinner();
        rMale = new javax.swing.JRadioButton();
        tCity = new javax.swing.JTextField();
        tPhone_no = new javax.swing.JTextField();
        lCity = new javax.swing.JLabel();
        lPhone_no = new javax.swing.JLabel();
        lSex = new javax.swing.JLabel();
        lAge = new javax.swing.JLabel();
        lName = new javax.swing.JLabel();
        tName = new javax.swing.JTextField();
        bSubmit = new javax.swing.JButton();
        bReset = new javax.swing.JButton();
        lUsername = new javax.swing.JLabel();
        tUsername = new javax.swing.JTextField();
        lPass = new javax.swing.JLabel();
        tPass = new javax.swing.JPasswordField();
        lConfirmpass = new javax.swing.JLabel();
        tConfirmpass = new javax.swing.JPasswordField();
        comboState = new javax.swing.JComboBox();
        lHeading = new javax.swing.JLabel();
        lWarning = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BloodBank-Donor Registration");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lState.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        lState.setText("State");

        genderButtonGroup.add(rFemale);
        rFemale.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        rFemale.setText("Female");

        sAge.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N

        genderButtonGroup.add(rMale);
        rMale.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        rMale.setText("Male");

        tCity.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N

        tPhone_no.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N

        lCity.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        lCity.setText("City");

        lPhone_no.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        lPhone_no.setText("Phone_no");

        lSex.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        lSex.setText("Gender");

        lAge.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        lAge.setText("Age");

        lName.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        lName.setText("Name");

        tName.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N

        bSubmit.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        bSubmit.setText("Submit");
        bSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSubmitActionPerformed(evt);
            }
        });

        bReset.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        bReset.setText("Reset");
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });

        lUsername.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        lUsername.setText("Username");

        tUsername.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N

        lPass.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        lPass.setText("Password");

        tPass.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N

        lConfirmpass.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        lConfirmpass.setText("Confirm Password");

        tConfirmpass.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N

        comboState.setEditable(true);
        comboState.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        comboState.setMaximumRowCount(28);
        comboState.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Karnataka", "Kerala", "Tamil Nadu", "Maharashtra", "Other" }));

        javax.swing.GroupLayout pFieldPanelLayout = new javax.swing.GroupLayout(pFieldPanel);
        pFieldPanel.setLayout(pFieldPanelLayout);
        pFieldPanelLayout.setHorizontalGroup(
            pFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFieldPanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(bSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(bReset, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFieldPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lPhone_no)
                    .addComponent(lSex))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tPhone_no, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pFieldPanelLayout.createSequentialGroup()
                        .addGroup(pFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sAge, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rMale))
                        .addGap(18, 18, 18)
                        .addComponent(rFemale)))
                .addContainerGap())
            .addGroup(pFieldPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pFieldPanelLayout.createSequentialGroup()
                        .addComponent(lAge)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFieldPanelLayout.createSequentialGroup()
                        .addGroup(pFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lName)
                            .addComponent(lConfirmpass)
                            .addComponent(lPass, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lUsername))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tName, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addComponent(tConfirmpass)
                            .addComponent(tPass)
                            .addComponent(tUsername))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFieldPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lCity)
                    .addComponent(lState))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tCity)
                    .addComponent(comboState, 0, 222, Short.MAX_VALUE))
                .addContainerGap())
        );

        pFieldPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tCity, tConfirmpass, tName, tPass, tPhone_no, tUsername});

        pFieldPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bReset, bSubmit});

        pFieldPanelLayout.setVerticalGroup(
            pFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFieldPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lUsername)
                    .addComponent(tUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPass)
                    .addComponent(tPass, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lConfirmpass)
                    .addComponent(tConfirmpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lName)
                    .addComponent(tName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lAge)
                    .addComponent(sAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lSex)
                    .addComponent(rMale)
                    .addComponent(rFemale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPhone_no)
                    .addComponent(tPhone_no, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lCity, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lState)
                    .addComponent(comboState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bReset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pFieldPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tCity, tConfirmpass, tName, tPass, tPhone_no, tUsername});

        pFieldPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bReset, bSubmit});

        lHeading.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        lHeading.setText("Blood Donor Registration Form");

        lWarning.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        lWarning.setForeground(new java.awt.Color(51, 51, 255));
        lWarning.setText("Warning");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(lHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lWarning)
                            .addComponent(pFieldPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pFieldPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lWarning)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
        tUsername.setText(null);
        tPass.setText(null);
        tConfirmpass.setText(null);
        tName.setText(null);
        sAge.setValue(20);
        rMale.setSelected(true);
        // genderButtonGroup.setSelected();
        tPhone_no.setText(null);
        tCity.setText(null);
        comboState.setSelectedIndex(0);

    }//GEN-LAST:event_bResetActionPerformed

    private void bSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSubmitActionPerformed
        lWarning.setText(null);
        setSubmittedUsername(tUsername.getText().toString());
        setSubmittedPassword(tPass.getText().toString());
        setSubmittedConfirmpassword(tConfirmpass.getText().toString());

        setSubmittedFullName(tName.getText().toString());
        setSubmittedAge(Integer.parseInt(sAge.getValue().toString()));
        setSubmittedGender(genderButtonGroup.getSelection().getActionCommand());
        setSubmittedPhone(tPhone_no.getText().toString());
        setSubmittedCity(tCity.getText().toString());
        setSubmittedState(comboState.getSelectedItem().toString());

        if (getSubmittedUsername().isEmpty()) {
            lWarning.setText("Username not entered");
        } else if (getSubmittedPassword().isEmpty()) {
            lWarning.setText("Password not entered");
        } else if (getSubmittedConfirmpassword().isEmpty()) {
            lWarning.setText("Confirm Password not entered");
        } else if (!submittedPassword.equals(submittedConfirmpassword)) {
            lWarning.setText("Password Not Equal ");

        } else if (getSubmittedFullName().isEmpty()) {
            lWarning.setText("Please provide full Name");
        } else if (getSubmittedAge() < 18) {
            lWarning.setText("We do not accept blood from kids!");
        } else if (getSubmittedPhone().length() != 10) {
            lWarning.setText("Phone Number is invalid... TRY AGAIN");
        } else {

            lWarning.setText(null);
            BusinessLogic.UserRegistration register = new BusinessLogic.UserRegistration();
            register.setUsername(getSubmittedUsername());
            register.setPassword(getSubmittedPassword());

            returnFromDonorBL = register.fnToInsertUser();
            if (returnFromDonorBL) {
                lWarning.setText("User Created ");
            } else {
                lWarning.setText("Database Error");

            }

            BusinessLogic.Donor donor = new BusinessLogic.Donor();
            donor.setName(getSubmittedFullName());
            donor.setAge(getSubmittedAge());
            donor.setGender(getSubmittedGender());
            donor.setPhone_no(getSubmittedPhone());
            donor.setAddress(getSubmittedCity()+" "+getSubmittedState());
            returnFromDonorRegistrationBL = donor.insertDonor();
            if (returnFromDonorRegistrationBL) {
                lWarning.setText("Insertion Successfull");
            } else {
                lWarning.setText("Database Error");
            }
        }
        System.out.println(getSubmittedPassword());
        System.out.println(getSubmittedConfirmpassword());
        System.out.println(getSubmittedUsername());
        System.out.println("Name=" + getSubmittedFullName());
        System.out.println("Age=" + getSubmittedAge());
        System.out.println("Gender=" + getSubmittedGender());
        System.out.println("Phone_no=" + getSubmittedPhone());
        System.out.println("City=" + getSubmittedCity());
        System.out.println("State=" + getSubmittedState());
    }//GEN-LAST:event_bSubmitActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bReset;
    private javax.swing.JButton bSubmit;
    private javax.swing.JComboBox comboState;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JLabel lAge;
    private javax.swing.JLabel lCity;
    private javax.swing.JLabel lConfirmpass;
    private javax.swing.JLabel lHeading;
    private javax.swing.JLabel lName;
    private javax.swing.JLabel lPass;
    private javax.swing.JLabel lPhone_no;
    private javax.swing.JLabel lSex;
    private javax.swing.JLabel lState;
    private javax.swing.JLabel lUsername;
    private javax.swing.JLabel lWarning;
    private javax.swing.JPanel pFieldPanel;
    private javax.swing.JRadioButton rFemale;
    private javax.swing.JRadioButton rMale;
    private javax.swing.JSpinner sAge;
    private javax.swing.JTextField tCity;
    private javax.swing.JPasswordField tConfirmpass;
    private javax.swing.JTextField tName;
    private javax.swing.JPasswordField tPass;
    private javax.swing.JTextField tPhone_no;
    private javax.swing.JTextField tUsername;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the submittedFullName
     */
    public String getSubmittedFullName() {
        return submittedFullName;
    }

    /**
     * @param submittedFullName the submittedFullName to set
     */
    public void setSubmittedFullName(String submittedFullName) {
        this.submittedFullName = submittedFullName;
    }

    /**
     * @return the submittedAge
     */
    public int getSubmittedAge() {
        return submittedAge;
    }

    /**
     * @param submittedAge the submittedAge to set
     */
    public void setSubmittedAge(int submittedAge) {
        this.submittedAge = submittedAge;
    }

    /**
     * @return the submittedGender
     */
    public String getSubmittedGender() {
        return submittedGender;
    }

    /**
     * @param submittedGender the submittedGender to set
     */
    public void setSubmittedGender(String submittedGender) {
        this.submittedGender = submittedGender;
    }

    /**
     * @return the submittedPhone
     */
    public String getSubmittedPhone() {
        return submittedPhone;
    }

    /**
     * @param submittedPhone the submittedPhone to set
     */
    public void setSubmittedPhone(String submittedPhone) {
        this.submittedPhone = submittedPhone;
    }

    /**
     * @return the submittedCity
     */
    public String getSubmittedCity() {
        return submittedCity;
    }

    /**
     * @param submittedCity the submittedCity to set
     */
    public void setSubmittedCity(String submittedCity) {
        this.submittedCity = submittedCity;
    }

    /**
     * @return the submittedState
     */
    public String getSubmittedState() {
        return submittedState;
    }

    /**
     * @param submittedState the submittedState to set
     */
    public void setSubmittedState(String submittedState) {
        this.submittedState = submittedState;
    }
}
