/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Donorform.java
 *
 * Created on Jan 3, 2014, 11:56:43 PM
 */

package forms;

/**
 *
 * @author Administrator
 */
public class Donorform extends javax.swing.JFrame {
    String Name;
    int Age;
    String Gender;
    String Phone_no;
    String City;
    String State;
    boolean returnFromBL;

    /** Creates new form Donor form */
    public Donorform() {
        initComponents();
        lWarning.setText(null);
        sAge.setValue(20);
        rMale.setSelected(true);
        rMale.setActionCommand("Male");
        rFemale.setActionCommand("Female");
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButtonGroup = new javax.swing.ButtonGroup();
        pFieldPanel = new javax.swing.JPanel();
        lState = new javax.swing.JLabel();
        rFemale = new javax.swing.JRadioButton();
        sAge = new javax.swing.JSpinner();
        rMale = new javax.swing.JRadioButton();
        tCity = new javax.swing.JTextField();
        tPhone_no = new javax.swing.JTextField();
        lCity = new javax.swing.JLabel();
        lPhone_no = new javax.swing.JLabel();
        lSex = new javax.swing.JLabel();
        lAge = new javax.swing.JLabel();
        lName = new javax.swing.JLabel();
        tState = new javax.swing.JTextField();
        tName = new javax.swing.JTextField();
        bSubmit = new javax.swing.JButton();
        bReset = new javax.swing.JButton();
        lHeading = new javax.swing.JLabel();
        lWarning = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lState.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        lState.setText("State");

        genderButtonGroup.add(rFemale);
        rFemale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rFemale.setText("Female");

        sAge.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        genderButtonGroup.add(rMale);
        rMale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rMale.setText("Male");

        tCity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tPhone_no.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lCity.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        lCity.setText("City");

        lPhone_no.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        lPhone_no.setText("Phone_no");

        lSex.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        lSex.setText("Gender");

        lAge.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        lAge.setText("Age");

        lName.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        lName.setText("Name");

        tState.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        bSubmit.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        bSubmit.setText("Submit");
        bSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSubmitActionPerformed(evt);
            }
        });

        bReset.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        bReset.setText("Reset");
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pFieldPanelLayout = new javax.swing.GroupLayout(pFieldPanel);
        pFieldPanel.setLayout(pFieldPanelLayout);
        pFieldPanelLayout.setHorizontalGroup(
            pFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFieldPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pFieldPanelLayout.createSequentialGroup()
                        .addComponent(lName)
                        .addGap(33, 33, 33))
                    .addComponent(lSex)
                    .addComponent(lPhone_no)
                    .addComponent(lCity)
                    .addComponent(lAge)
                    .addComponent(lState))
                .addGap(64, 64, 64)
                .addGroup(pFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pFieldPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(pFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sAge, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pFieldPanelLayout.createSequentialGroup()
                                .addComponent(rMale)
                                .addGap(18, 18, 18)
                                .addComponent(rFemale))
                            .addComponent(tCity, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(tName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(tState, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                    .addGroup(pFieldPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tPhone_no, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pFieldPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(bSubmit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(bReset)
                .addGap(74, 74, 74))
        );

        pFieldPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tName, tPhone_no});

        pFieldPanelLayout.setVerticalGroup(
            pFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFieldPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lAge))
                .addGap(6, 6, 6)
                .addGroup(pFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lSex)
                    .addComponent(rMale)
                    .addComponent(rFemale))
                .addGap(10, 10, 10)
                .addGroup(pFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tPhone_no, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPhone_no))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lCity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lState))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSubmit)
                    .addComponent(bReset))
                .addContainerGap())
        );

        pFieldPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tName, tPhone_no});

        lHeading.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        lHeading.setText("Donor personel Info");

        lWarning.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        lWarning.setForeground(new java.awt.Color(51, 51, 255));
        lWarning.setText("Warning");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(lHeading))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(lWarning)))
                .addContainerGap(233, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(pFieldPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lHeading)
                .addGap(29, 29, 29)
                .addComponent(pFieldPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(lWarning)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
        tName.setText(null);
        sAge.setValue(20);
        rMale.setSelected(true);
       // genderButtonGroup.setSelected();
        tPhone_no.setText(null);
        tCity.setText(null);
        tState.setText(null);

    }//GEN-LAST:event_bResetActionPerformed

    private void bSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSubmitActionPerformed
        lWarning.setText(null);
        Name=tName.getText().toString();
        Age= Integer.parseInt( sAge.getValue().toString());
        Gender=genderButtonGroup.getSelection().getActionCommand();
        Phone_no=tPhone_no.getText().toString();
        City=tCity.getText().toString();
        State=tState.getText().toString();
        if(Name.isEmpty())
        {
            lWarning.setText("Name cannot be null");
        }
        else if(Age<18)
        {
            lWarning.setText("You cannot donate");
        }
        else if(Phone_no.length()!=10)
        {
            lWarning.setText("Phone Number is invalid... TRY AGAIN");
        }
        else {
                BusinessLogic.Donor donor=new  BusinessLogic.Donor();
                returnFromBL=donor.insertDonor();
                if(returnFromBL){
                    lWarning.setText("Insertion Successfull");
                }else {
                    lWarning.setText("Database Error");
                }
        }
        System.out.println("Name="+Name);
        System.out.println("Age="+Age);
        System.out.println("Gender="+Gender);
        System.out.println("Phone_no="+Phone_no);
        System.out.println("City="+City);
        System.out.println("State="+State);
    }//GEN-LAST:event_bSubmitActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Donorform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bReset;
    private javax.swing.JButton bSubmit;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JLabel lAge;
    private javax.swing.JLabel lCity;
    private javax.swing.JLabel lHeading;
    private javax.swing.JLabel lName;
    private javax.swing.JLabel lPhone_no;
    private javax.swing.JLabel lSex;
    private javax.swing.JLabel lState;
    private javax.swing.JLabel lWarning;
    private javax.swing.JPanel pFieldPanel;
    private javax.swing.JRadioButton rFemale;
    private javax.swing.JRadioButton rMale;
    private javax.swing.JSpinner sAge;
    private javax.swing.JTextField tCity;
    private javax.swing.JTextField tName;
    private javax.swing.JTextField tPhone_no;
    private javax.swing.JTextField tState;
    // End of variables declaration//GEN-END:variables

}
