/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

/**
 *
 * @author DELL
 */
public class FirstPageForm extends javax.swing.JFrame {

    /**
     * Creates new form FirstPageForm
     */
    public FirstPageForm() {
        initComponents();
        initiateComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegisterDonor = new javax.swing.JLabel();
        lBloodBankName = new javax.swing.JLabel();
        lTagline = new javax.swing.JLabel();
        bLoginHere = new javax.swing.JButton();
        lQuoteFirstline = new javax.swing.JLabel();
        lQuoteSecondline = new javax.swing.JLabel();
        lQuoteThirdLine = new javax.swing.JLabel();
        lTips = new javax.swing.JLabel();
        lMisconception = new javax.swing.JLabel();
        bBloodInfo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Blood Bank Management System");

        RegisterDonor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/blood_bank.gif"))); // NOI18N
        RegisterDonor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegisterDonor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterDonorMouseClicked(evt);
            }
        });

        lBloodBankName.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        lBloodBankName.setForeground(java.awt.Color.red);
        lBloodBankName.setText("Some Name Blood Bank");

        lTagline.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lTagline.setForeground(new java.awt.Color(17, 124, 17));
        lTagline.setText("We are Always Ready for donating blood...");

        bLoginHere.setFont(new java.awt.Font("Ubuntu Light", 1, 14)); // NOI18N
        bLoginHere.setText("Login here ");
        bLoginHere.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bLoginHere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginHereActionPerformed(evt);
            }
        });

        lQuoteFirstline.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lQuoteFirstline.setForeground(java.awt.Color.red);
        lQuoteFirstline.setText("\"Saving the world isn't Easy");

        lQuoteSecondline.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lQuoteSecondline.setForeground(java.awt.Color.red);
        lQuoteSecondline.setText("Saving a Life IS.");

        lQuoteThirdLine.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lQuoteThirdLine.setForeground(java.awt.Color.red);
        lQuoteThirdLine.setText("Donating 1 Pint of blood can save upto 3 lives.\"");

        lTips.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
        lTips.setForeground(java.awt.Color.blue);
        lTips.setText("Tips on Blood Donating");
        lTips.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lTips.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lTipsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lTipsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lTipsMouseExited(evt);
            }
        });

        lMisconception.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
        lMisconception.setForeground(java.awt.Color.blue);
        lMisconception.setText("Misconception about Donating Blood");
        lMisconception.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lMisconception.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lMisconceptionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lMisconceptionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lMisconceptionMouseExited(evt);
            }
        });

        bBloodInfo.setFont(new java.awt.Font("Ubuntu Light", 1, 14)); // NOI18N
        bBloodInfo.setText("Get Blood Info");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lQuoteFirstline)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RegisterDonor)
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bLoginHere)
                                    .addComponent(bBloodInfo)))
                            .addComponent(lQuoteSecondline)
                            .addComponent(lQuoteThirdLine)
                            .addComponent(lTips)
                            .addComponent(lMisconception)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lTagline)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lBloodBankName)
                                .addGap(21, 21, 21)))))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bBloodInfo, bLoginHere});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lBloodBankName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lTagline)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(RegisterDonor)
                        .addGap(27, 27, 27)
                        .addComponent(lQuoteFirstline)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lQuoteSecondline))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(bLoginHere, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bBloodInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lQuoteThirdLine)
                .addGap(25, 25, 25)
                .addComponent(lTips)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lMisconception)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bBloodInfo, bLoginHere});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lTipsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lTipsMouseEntered
        lTips.setForeground(java.awt.Color.green);
    }//GEN-LAST:event_lTipsMouseEntered

    private void lTipsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lTipsMouseExited
        lTips.setForeground(java.awt.Color.blue);
    }//GEN-LAST:event_lTipsMouseExited

    private void lMisconceptionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lMisconceptionMouseEntered
        lMisconception.setForeground(java.awt.Color.green);
    }//GEN-LAST:event_lMisconceptionMouseEntered

    private void lMisconceptionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lMisconceptionMouseExited
        lMisconception.setForeground(java.awt.Color.blue);
    }//GEN-LAST:event_lMisconceptionMouseExited

    private void RegisterDonorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterDonorMouseClicked
        Loginform login=new Loginform();
        login.setVisible(true);
        DonorRegistrationForm createnew = new DonorRegistrationForm();
        createnew.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegisterDonorMouseClicked

    private void bLoginHereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginHereActionPerformed
        Loginform login=new Loginform();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bLoginHereActionPerformed

    private void lTipsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lTipsMouseClicked
        DisplayTipsForm dispTips=new DisplayTipsForm();
        dispTips.setVisible(true);
    }//GEN-LAST:event_lTipsMouseClicked

    private void lMisconceptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lMisconceptionMouseClicked
        DisplayMisconceptionForm misconcept=new DisplayMisconceptionForm();
        misconcept.setVisible(true);
    }//GEN-LAST:event_lMisconceptionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstPageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstPageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstPageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstPageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FirstPageForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RegisterDonor;
    private javax.swing.JButton bBloodInfo;
    private javax.swing.JButton bLoginHere;
    private javax.swing.JLabel lBloodBankName;
    private javax.swing.JLabel lMisconception;
    private javax.swing.JLabel lQuoteFirstline;
    private javax.swing.JLabel lQuoteSecondline;
    private javax.swing.JLabel lQuoteThirdLine;
    private javax.swing.JLabel lTagline;
    private javax.swing.JLabel lTips;
    // End of variables declaration//GEN-END:variables

    private void initiateComponents() {
        //textAreaQuotes.setText("Saving the world isn't Easy \nSaving a Life IS. \nDonating 1 Pint of blood can save upto 3 lives.");
    }
}
