/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

/**
 *
 * @author Administrator
 */
public class UsernameForm extends javax.swing.JFrame {

    /**
     * Creates new form Username
     */
    private String submittedUsername;
    private String submittedPassword;
    private String submittedConfirmpassword;
    boolean returnfromBL;

    public UsernameForm() {
        initComponents();
        lWarning.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jColorChooser2 = new javax.swing.JColorChooser();
        jPanel1 = new javax.swing.JPanel();
        lConfirmpass = new javax.swing.JLabel();
        lUsername = new javax.swing.JLabel();
        tUsername = new javax.swing.JTextField();
        lPass = new javax.swing.JLabel();
        bSubmit = new javax.swing.JButton();
        bReset = new javax.swing.JButton();
        tPass = new javax.swing.JPasswordField();
        tConfirmpass = new javax.swing.JPasswordField();
        lUserlogin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lWarning = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lConfirmpass.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        lConfirmpass.setText("Confirm Password");

        lUsername.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        lUsername.setText("Username");

        tUsername.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N

        lPass.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        lPass.setText("Password");

        bSubmit.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        bSubmit.setText("Continue");
        bSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSubmitActionPerformed(evt);
            }
        });

        bReset.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        bReset.setText("Reset");
        bReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bResetMouseClicked(evt);
            }
        });
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lConfirmpass)
                                .addGap(18, 18, 18)
                                .addComponent(tConfirmpass))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lPass, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lUsername))
                                .addGap(72, 72, 72)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tPass, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(bSubmit)
                        .addGap(104, 104, 104)
                        .addComponent(bReset)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lUsername))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tPass, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPass))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lConfirmpass)
                    .addComponent(tConfirmpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSubmit)
                    .addComponent(bReset))
                .addContainerGap())
        );

        lUserlogin.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        lUserlogin.setText("User Login");

        lWarning.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        lWarning.setForeground(java.awt.Color.blue);
        lWarning.setText("Warning");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(lUserlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lWarning)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lUserlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lWarning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bResetMouseClicked

    }//GEN-LAST:event_bResetMouseClicked

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
        tUsername.setText(null);
        tPass.setText(null);
        tConfirmpass.setText(null);

    }//GEN-LAST:event_bResetActionPerformed

    private void bSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSubmitActionPerformed

        setSubmittedUsername(tUsername.getText().toString());
        setSubmittedPassword(tPass.getPassword().toString());
        setSubmittedConfirmpassword(tConfirmpass.getPassword().toString());
        System.out.println(getSubmittedPassword());
        System.out.println(getSubmittedConfirmpassword());
        System.out.println(getSubmittedUsername());

        if (getSubmittedUsername().isEmpty()) {
            lWarning.setText("Username not entered");
        } else if (getSubmittedPassword().isEmpty()) {
            lWarning.setText("Password not entered");
        } else if (getSubmittedConfirmpassword().isEmpty()) {
            lWarning.setText("Confirm Password not entered");
        } else if (!submittedPassword.equals(submittedConfirmpassword)) {
            lWarning.setText("Error Occured!!");
            
        } else {
            lWarning.setText(null);
            BusinessLogic.UserRegistration register=new BusinessLogic.UserRegistration();
            
            returnfromBL=register.fnToInsertUser();
             if(returnfromBL){
                lWarning.setText("User Created");
            } else {
                 lWarning.setText("Databse Error");
            
            }
        }
        
       

    }//GEN-LAST:event_bSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsernameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsernameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsernameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsernameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsernameForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bReset;
    private javax.swing.JButton bSubmit;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JColorChooser jColorChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lConfirmpass;
    private javax.swing.JLabel lPass;
    private javax.swing.JLabel lUserlogin;
    private javax.swing.JLabel lUsername;
    private javax.swing.JLabel lWarning;
    private javax.swing.JPasswordField tConfirmpass;
    private javax.swing.JPasswordField tPass;
    private javax.swing.JTextField tUsername;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the submittedUsername
     */
    public String getSubmittedUsername() {
        return submittedUsername;
    }

    /**
     * @param submittedUsername the submittedUsername to set
     */
    public void setSubmittedUsername(String submittedUsername) {
        this.submittedUsername = submittedUsername;
    }

    /**
     * @return the submittedPassword
     */
    public String getSubmittedPassword() {
        return submittedPassword;
    }

    /**
     * @param submittedPassword the submittedPassword to set
     */
    public void setSubmittedPassword(String submittedPassword) {
        this.submittedPassword = submittedPassword;
    }

    /**
     * @return the submittedConfirmpassword
     */
    public String getSubmittedConfirmpassword() {
        return submittedConfirmpassword;
    }

    /**
     * @param submittedConfirmpassword the submittedConfirmpassword to set
     */
    public void setSubmittedConfirmpassword(String submittedConfirmpassword) {
        this.submittedConfirmpassword = submittedConfirmpassword;
    }
}
